### ISSUE TITLE
Can I manage the version of subprojects separately?

### ISSUE THREAD

**Issue by sappho192** [kekyo/CenterCLR.RelaxVersioner#16]
Hello,

I'm trying to use RelaxVersioner in following solution structure:
```
Soution A
↳ Project 1
↳ Project 2
↳ Project 3
```

Before developing this solution, I developed different solution which contains only one project and everything was fine.
But I can't find out how can I handle the version of each project separately.

Do you have any tips on this?

Thank you 😀

**Comment by kekyo** [comment]
Thank you for using RelaxVersioner!
RelaxVersioner manages versions on a Git repository basis. For example, if you tag a commit as `1.0.0`, all projects contained within that commit will have the same `1.0.0` version.

If you want to apply different versions each projects, you have to separate Git repositories.
It may not be very realistic, but you can...

For example, use Git submodules for each project unit to integrate them.
In your example, you have separate repositories for each of `Project1`, `Project2`, and `Project3`, and add them as submodules to the repository where the solution exists.

----

### Incredible (not fiction) story

This is a supplemental note. In the past I have handled development projects where the operation was to apply versions individually to hundreds of existing projects (this was back in the VC++ days). The result of trying to strictly manage versioning was a huge (and incomprehensible) control ledger of version combinations and behavior verification results, and we spent most of our time managing the ledger rather than designing and developing. (It's really not funny!)

The lesson I learned here is that "humans cannot control the combination of versions; they can only control the versioning of the project. It makes no sense to version individually, since the number of combinations grows exponentially and you can't even evaluate all of them" 😄

**Comment by sappho192** [comment]
Thank you for your advice. 😄  

With considering your invaluable story, I decided to use one unique version for multiple projects in one solution.
Since the projects are thightly related with each other (and that's why they are in one solution), single version still makes sense.

Even huge project like Windows uses single version with a build number and.... yes. Single version, mono-repo, there're always a reason 🤣
